### ISSUE TITLE
What variables to select from the confounder file for betaseries analyses?

### ISSUE THREAD

**Issue by LilianYou** [HBClab/NiBetaSeries#326]
Dear expert,

When using regressors, I'm wondering what variables shall I select from the confounder file that's acquired from fmriprep? For example, the file from each run includes different numbers of “non-steady-state-outliers” columns, shall I include or drop them?

**Comment by jdkent** [comment]
There are a lot of differing opinions on which confounds to choose, I like to include confounds that attempt to measure: motion (FD, DVARS, motion parameters, ICA-AROMA), scanner noise (non-steady-state), and non-neuronal physiological signal (white_matter, csf).

If you know how many volumes you would like to consider `non-steady-state` for all participants, you can specify the number of volumes with the `--dummy-scans` in fmriprep.

**Comment by LilianYou** [comment]
James: I don't have a particular reason for selecting `non-steady-state` volumes. Would keep all `non-steady-state` columns (varying volume for different subjects) yield worse nibetaseries result than drop all of them?

**Comment by jdkent** [comment]
I haven't tested adding a variable number of non-steady state volumes to measure it's impact on beta series correlations, so I couldn't say for sure whether keeping or dropping `non-steady-state` volumes would yield better results.

If you know the MR physicist that collected your data, they should be able to tell you how many volumes need to be collected before the magnet reaches a steady-state.

My armchair (i.e., untested) prediction would be that it would not matter much either way if the first event occurred after the scanner reached a steady state. The increased signal intensity during the beginning could increase the intercept (modeled baseline signal), but beta series correlations do not rely on the magnitude of a BOLD response relative to baseline, they only rely on the variance of the BOLD response across events, and changing the intercept should only impact mean, not variance.

However, if an event occurs before steady-state is reached, then I would expect there to be inflated correlations for whichever event occurred at that time point since every voxel could potentially have a large beta estimate in the same direction. If this is the case, I would highly recommend talking with the MR physicist to get a "ground truth" of how many non-steady-state volumes were in the protocol.

**Comment by LilianYou** [comment]
Hi James,

This is a very thorough answer. I'm glad to get to know more about the underlying principles of the beta series. It is really appreciated.

Best,
Lily
