### ISSUE TITLE
Take into account condition information for Least Squares Separate (LSS)

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#87]
**Is your feature request related to a problem? Please describe.**
In the current implementation of LSS, one trial is the "target" trial and every other trial is "other".
It would be false (in most cases) to say the conditions are not important towards explaining variance in the bold data (otherwise why would you have those conditions in the first place). Thus the "other" regressor may sub-optimally fit to the bold data.

**Describe the solution you'd like**
Instead of "target" and "other", have "target", "condition1", "condition2" ..., etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tsalo** [comment]
I'd love to take a crack at this, unless you already have some work underway to deal with it? 

Additionally, I believe that this change corresponds to the change in LSS methodology from [Mumford, Turner, Ashby, & Poldrack (2012)](https://www.sciencedirect.com/science/article/pii/S1053811911010081) to [Turner, Mumford, Poldrack, & Ashby (2012)](https://www.sciencedirect.com/science/article/abs/pii/S1053811912005459). It's been a while since I read both papers, but I think that retaining the original conditions was the main improvement made to LSS in the second one.

**Comment by jdkent** [comment]
Hi @tsalo, that would be fantastic, and thank you for the paper references. I'm about to merge #182, so this would be good test case to see if providing a prepackaged local development environment is useful, if you are up to trying it out. 

Otherwise installing nibetaseries locally isn't too much of a pain on unix based machines from my limited experience.

**Comment by tsalo** [comment]
This _should_ have been closed by #191, but I accidentally referenced the wrong issue 🤦‍♂. @jdkent would you mind closing it?
